### PR TITLE
Add support for Azure, OpenAI, Palm, Anthropic, Cohere, Replicate Models - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for models from all the above mentioned providers using https://github.com/BerriAI/litellm/

Here's a sample of how it's used:

```
from litellm import completion, acompletion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# async openai
response = acompletion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@madawei2699 can you please take a look at this PR? Happy to make any fixes + add documentation too😊

**Review by madawei2699 — APPROVED** [review]
LGTM

**Comment by ishaan-jaff** [comment]
@madawei2699 was there an issue you ran into when merging? If so happy to help fix it. I'm sorry if you ran into any errors

**Comment by madawei2699** [comment]
Seems it needs more server memory, I can't start it on a 256MB server.

**Pull request merged**
